---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "accessanalysis"
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pandas=1.5.3